"""Chronology exports (Phase 1.3): XLSX, DOCX, CSV, JSON.

Every export carries the run footer: tool version, extractor/model,
timestamp, unplaced and disputed counts. Nobody puts JSON in a trial
bundle. XLSX and DOCX are the formats legal work moves in.
"""

from __future__ import annotations

import csv
import json
from datetime import datetime, timezone
from pathlib import Path

from tdg_chrono import __version__
from tdg_chrono.chronology import Chronology, ChronologyEvent

_HEADERS = ["Date", "Precision", "Event", "Status", "Source doc(s)",
            "Quote(s)", "Disputed values", "Confidence"]


def _footer_lines(chron: Chronology) -> list[str]:
    meta = chron.meta
    counts = meta.get("counts", {})
    return [
        f"Generated by tdg-chrono {__version__}, "
        f"extractor: {meta.get('extractor', 'n/a')}, "
        f"run: {meta.get('timestamp', datetime.now(timezone.utc).isoformat(timespec='seconds'))}",
        f"{counts.get('events', len(chron.events))} events, "
        f"{counts.get('disputed', chron.disputed_count)} disputed, "
        f"{counts.get('unplaced', len(chron.unplaced))} unplaced (listed below the timeline; never dropped)",
        "Assistive output. Extraction is incomplete by design. Check every row "
        "against its quoted source before relying on it. Not legal advice.",
    ]


def _row(e: ChronologyEvent) -> list[str]:
    return [
        e.date.isoformat() if e.date else "",
        e.precision,
        e.label + (f"  [derived: {e.derivation}]" if e.derivation else ""),
        e.status,
        "; ".join(sorted({s.doc_id for s in e.sources})),
        " | ".join(f"[{s.doc_id}] {s.quote}" for s in e.sources),
        "; ".join(f"{v.value} ({', '.join(v.doc_ids)})" for v in e.disputed_values),
        f"{e.confidence:.2f}",
    ]


# ─── XLSX ────────────────────────────────────────────────────────────────

def to_xlsx(chron: Chronology, path: str | Path) -> Path:
    from openpyxl import Workbook
    from openpyxl.styles import Font, PatternFill, Alignment

    wb = Workbook()
    ws = wb.active
    ws.title = "Chronology"

    header_font = Font(bold=True, color="FFFFFF")
    header_fill = PatternFill("solid", fgColor="1F3864")
    disputed_fill = PatternFill("solid", fgColor="FCE4EC")
    derived_fill = PatternFill("solid", fgColor="E8F0FE")

    ws.append(_HEADERS)
    for c in ws[1]:
        c.font = header_font
        c.fill = header_fill

    for e in chron.events:
        ws.append(_row(e))
        if e.status == "disputed":
            for c in ws[ws.max_row]:
                c.fill = disputed_fill
        elif e.status == "derived":
            for c in ws[ws.max_row]:
                c.fill = derived_fill

    if chron.unplaced:
        ws.append([])
        ws.append(["UNPLACED (no resolvable date, review manually)"])
        ws[ws.max_row][0].font = Font(bold=True)
        for u in chron.unplaced:
            ev = u.event
            ws.append(["", ev.precision, ev.label, f"unplaced: {u.reason}",
                       "; ".join(sorted({s.doc_id for s in ev.sources})),
                       " | ".join(f"[{s.doc_id}] {s.quote}" for s in ev.sources),
                       "", f"{ev.confidence:.2f}"])

    ws.append([])
    for line in _footer_lines(chron):
        ws.append([line])
        ws[ws.max_row][0].font = Font(italic=True, size=9)

    n_rows = len(chron.events) + 1
    ws.freeze_panes = "A2"
    ws.auto_filter.ref = f"A1:H{n_rows}"
    widths = [12, 9, 40, 13, 18, 70, 28, 10]
    for i, w in enumerate(widths, start=1):
        ws.column_dimensions[chr(64 + i)].width = w
    for row in ws.iter_rows(min_row=2):
        for c in row:
            c.alignment = Alignment(vertical="top", wrap_text=True)

    path = Path(path)
    wb.save(path)
    return path


# ─── DOCX ────────────────────────────────────────────────────────────────

def to_docx(chron: Chronology, path: str | Path, title: str = "Chronology") -> Path:
    import docx
    from docx.shared import Pt

    doc = docx.Document()
    doc.add_heading(title, level=1)

    table = doc.add_table(rows=1, cols=5)
    table.style = "Table Grid"
    for cell, h in zip(table.rows[0].cells,
                       ["Date", "Event", "Status", "Source", "Quote"]):
        cell.text = h
        cell.paragraphs[0].runs[0].font.bold = True

    for e in chron.events:
        row = table.add_row().cells
        row[0].text = e.date.isoformat() if e.date else ""
        row[1].text = e.label + (f" [derived]" if e.status == "derived" else "")
        row[2].text = e.status if e.status != "disputed" else (
            "DISPUTED: " + " vs ".join(v.value for v in e.disputed_values))
        row[3].text = "; ".join(sorted({s.doc_id for s in e.sources}))
        row[4].text = " | ".join(f"[{s.doc_id}] {s.quote}" for s in e.sources)

    if chron.unplaced:
        doc.add_heading("Unplaced items", level=2)
        for u in chron.unplaced:
            doc.add_paragraph(
                f"{u.event.label}: {u.reason} "
                f"({'; '.join(sorted({s.doc_id for s in u.event.sources}))})",
                style="List Bullet")

    doc.add_paragraph()
    for line in _footer_lines(chron):
        p = doc.add_paragraph(line)
        p.runs[0].font.size = Pt(8)
        p.runs[0].font.italic = True

    path = Path(path)
    doc.save(path)
    return path


# ─── CSV / JSON ──────────────────────────────────────────────────────────

def to_csv(chron: Chronology, path: str | Path) -> Path:
    path = Path(path)
    with path.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(_HEADERS)
        for e in chron.events:
            w.writerow(_row(e))
        w.writerow([])
        for u in chron.unplaced:
            w.writerow(["", u.event.precision, u.event.label,
                        f"unplaced: {u.reason}",
                        "; ".join(sorted({s.doc_id for s in u.event.sources})),
                        " | ".join(s.quote for s in u.event.sources), "", ""])
        w.writerow([])
        for line in _footer_lines(chron):
            w.writerow([line])
    return path


def to_json(chron: Chronology, path: str | Path) -> Path:
    path = Path(path)
    payload = chron.to_dict()
    payload["meta"]["footer"] = _footer_lines(chron)
    path.write_text(json.dumps(payload, indent=2))
    return path


EXPORTERS = {"xlsx": to_xlsx, "docx": to_docx, "csv": to_csv, "json": to_json}
